### ISSUE TITLE
Alert tracking page

### ISSUE THREAD

**Issue by Flottegurke** [The-Bug-Bashers/SAAI#8]
The alerting page should be able to track the status of an Outgoing allert and show it to the Person allerting the Paramedics

The Page should be able to do:

- [x] If the alert did not work:
  - [x] Display: "Der Alarm konnte nicht versendet werden, bitte versuchen sie es nocheinmal, wenn es wiederholt nicht funktioniert gehen sie bitte zu Lerhaus 7-10 und fragen nach einem Schulsanitäter"
  - [x] Button to resend the Alert
  - [x] Display the response from the API

- [x] If the Alert worked
  - [x] save the Alert ID and pass it to the AlertTracking page
  - [x] Display: "Die Schulsanitäter wurden erfolgreich alarmiert"
  - [x] Request alert data using the /alertinfo endpoint while providing the Alert ID
  - [x] Display names of alerted Paramedics
  - [ ] Display status of alerted Paramedics
  - [ ] Display how many school paramedics accepted
    - [ ] Display: "Es `sind/ist`  `Number of paramedics that accepted` Schulsanitäter auf dem Weg zu ihnen, bitte warten sie an dem von ihnen angegebenen Ort"
